#!/usr/bin/env python3
"""Generate main/emoji_table.h from tools/emoji-data.json.

Usage:
    python tools/gen-emoji-table.py tools/emoji-data.json main/emoji_table.h
"""
import json
import sys

GROUPS = [
    "Smileys & Emotion", "People & Body", "Animals & Nature", "Food & Drink",
    "Travel & Places", "Activities", "Objects", "Symbols", "Flags",
]


def c_string_escape(s):
    # ASCII passthrough + \ooo (zero-padded octal) per UTF-8 byte for non-ASCII.
    # Octal escapes are grammar-limited to exactly 3 digits, so zero-padding
    # makes them safe to sit next to a literal digit afterwards (unlike \xHH,
    # which keeps consuming hex digits and can swallow the next character).
    result = []
    for ch in s:
        cp = ord(ch)
        if ch in ('"', '\\'):
            result.append('\\' + ch)
        elif 0x20 <= cp < 0x7F:
            result.append(ch)
        else:
            for b in ch.encode('utf-8'):
                result.append('\\%03o' % b)
    return ''.join(result)


def main():
    data_path, out_path = sys.argv[1:3]
    with open(data_path, encoding='utf-8') as f:
        items = json.load(f)

    items.sort(key=lambda d: d['key'])

    group_index = {name: i for i, name in enumerate(GROUPS)}

    lines = []
    lines.append('// Generated by tools/gen-emoji-table.py from tools/emoji-data.json. Do not edit by hand.')
    lines.append('#pragma once')
    lines.append('')
    lines.append('#include <stdint.h>')
    lines.append('')
    lines.append('typedef struct {')
    lines.append('    const char *key;')
    lines.append('    const char *utf8;')
    lines.append('    const char *label;')
    lines.append('    uint8_t     group;')
    lines.append('} emoji_entry_t;')
    lines.append('')
    lines.append(f'#define EMOJI_GROUP_COUNT {len(GROUPS)}')
    lines.append('static const char *const EMOJI_GROUP_NAMES[EMOJI_GROUP_COUNT] = {')
    lines.append('    ' + ', '.join('"%s"' % g for g in GROUPS))
    lines.append('};')
    lines.append('')
    lines.append(f'#define EMOJI_TABLE_COUNT {len(items)}')
    lines.append('// Sorted by key for binary search.')
    lines.append('static const emoji_entry_t EMOJI_TABLE[EMOJI_TABLE_COUNT] = {')
    for it in items:
        key = it['key']
        cps = [int(c, 16) for c in key.split('-')]
        glyph = it['glyph']
        label = it['name']
        gi = group_index[it['group']]
        lines.append('    {"%s", "%s", "%s", %d},' % (
            key, c_string_escape(glyph), c_string_escape(label), gi))
    lines.append('};')
    lines.append('')

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    print(f"Wrote {len(items)} entries to {out_path}")


if __name__ == '__main__':
    main()
